<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CycloneKallApp</AssemblyName>
    <RootNamespace>CycloneKallApp</RootNamespace>
    <ApplicationTitle>Cyclone Kall App</ApplicationTitle>
    <Product>Cyclone Kall App</Product>
    <AssemblyTitle>Cyclone Kall App</AssemblyTitle>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>